services:
  - type: web
    name: travelita-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://ashik-muhammed.github.io
      - key: PORT
        value: 5000
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
    buildFilter:
      paths:
        - backend/**
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: DENY
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    healthCheck:
      httpPath: /health
      port: 5000
      initialDelay: 10 